name: CI-CD Docker Azure

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          pip install -r requirements.txt
          pytest

      # 🐳 Docker build
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/hello-python:latest .

      # 🔐 登录 ACR
      - name: Docker login
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_NAME }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # 🚀 Push 镜像
      - name: Push image
        run: |
          docker push ${{ secrets.ACR_NAME }}/hello-python:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_XXX }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_XXX }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_XXX }}

      # 🐳 更新 Web App 使用 Docker
      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: hello-python-azure
          images: ${{ secrets.ACR_LOGIN_SERVER }}/hello-python:latest
