name: CI-CD Docker Azure

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 🧪 测试
      - name: Run tests
        run: |
          pip install -r requirements.txt
          pytest

      # 🐳 Docker build
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/hello-python:latest .

      # 🔐 登录 ACR（关键修复）
      - name: Docker login
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USER }} --password-stdin

      # 🚀 Push 镜像
      - name: Push image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/hello-python:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DEEB549CC1034292981FE37FC9118107 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_02965D2CA6E34AB197DB138D7DBCB33B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_17320AABE9A14CB8A2349162133C8956 }}

      - name: Deploy to Azure Web App (Container)
        uses: azure/webapps-deploy@v3
        with:
          app-name: hello-python-azure
          images: ${{ secrets.ACR_NAME }}.azurecr.io/hello-python:latest
